### ISSUE TITLE
consider changing the Middleware signature to use options pattern

### ISSUE THREAD

**Issue by posener** [mitchellh/go-server-timing#9]
The [options pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis):

* Instead of `func Middleware(next http.Handler, _ *MiddlewareOpts)` use `func Middleware(next http.Handler, _ ...MiddlewareOpts)`.
* Instead of `type MiddlewareOpts struct` have `type options struct` and `type MiddlewareOpts func(*options)`

Then, the call for the middleware won't have `nil` as second argument.

I know that this is a breaking change, but you might consider it.

**Comment by mitchellh** [comment]
I did consider the options pattern for that field. However, I've also maintained many libraries using the struct pattern and haven't yet fallen into any of the pitfalls noted in that blog post. There are arguments for aesthetics for sure but I also find it quite nice that you can find the documentation for all fields in one location (versus spread across implementing functions). Overall, I'd consider it a bit of a toss-up either way...

So, I'm against this currently because it would introduce a breaking change for what I consider zero value (aesthetics only currently). Its arguable that the value comes later and is greatest now since the breaking change is probably least disruptive early on in a project's life. But for me personally, I've never been hit by struct opts causing an issue so I'm inclined to not fear it.

I hope I've articulated my opinion, your suggestion isn't "wrong" but I think it does come down to opinion. Thank you!
